/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnz;

/**
 *
 * @author huany
 */
import java.util.Random; 
public class PNZFrame extends javax.swing.JFrame {
    String out = "";
    String target = "";
    String input = "";

    /**
     * Creates new form PNZFrame
     */
    public PNZFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        label1 = new java.awt.Label();
        NewGame = new javax.swing.JButton();
        ResultsField = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InputField = new java.awt.TextField();
        EnterBut = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        label1.setName("PNZ Game"); // NOI18N
        label1.setText("PNZ Game");

        NewGame.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        NewGame.setText("New Game");
        NewGame.setActionCommand("");
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameActionPerformed(evt);
            }
        });

        ResultsField.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setText("Input Box");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel2.setText("(No repeats or more than three digit inputs, will cause error message");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel3.setText("Results");

        InputField.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N

        EnterBut.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        EnterBut.setText("Enter");
        EnterBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(246, 246, 246))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(InputField, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterBut, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(ResultsField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InputField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnterBut, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ResultsField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        label1.getAccessibleContext().setAccessibleName("PNZ Game");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButActionPerformed
      input = InputField.getText();
      
        if (input.length() != 3 || input.substring(0, 1).equals(input.substring(1, 2)) || input.substring(0, 1).equals(input.substring(2, 3)) || input.substring(1, 2).equals(input.substring(2, 3))) {
            out += ("error, invalid input");
            out += "\n";
            ResultsField.setText(out);
            InputField.setText("");
        } else {
            target += (randomString());

            String result = evaluateGuess(target, input);
            displayResults(input, result);
               InputField.setText("");
        }
        System.out.println(target);

    }//GEN-LAST:event_EnterButActionPerformed

    private void NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameActionPerformed
 startnewGame();
    }//GEN-LAST:event_NewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PNZFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PNZFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PNZFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PNZFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PNZFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterBut;
    private java.awt.TextField InputField;
    private javax.swing.JButton NewGame;
    private java.awt.TextArea ResultsField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
Random random = new Random();

    public void startnewGame() {
        out = ""; //resets all global variables for new game
        ResultsField.setText(out);
        InputField.setText("");
        target = "";
        input = "";
         InputField.setEnabled(true);//allows them to input new numbers afer new game starts
          EnterBut.setEnabled(true);
    }

    char randomDigit() {

        int n = random.nextInt(10);//0 based, so chooses from 0 to 9
        n += 48; //unicode for numbers start at 48
        return (char) n; //must type cast int to char

    }

    String randomString() {
        char d1 = randomDigit(); // 1;//random.nextInt(10); 
        char d2 = randomDigit(); // 1;//random.nextInt(10); 

        while (true) {
            if (d2 != d1) {
                break;
            } else { //refinds digit 2 if it is equal to digit one to ensure no duplicates
                d2 = randomDigit();
            }
        }
        char d3 = randomDigit(); //random.nextInt(10); 
        while (true) {
            if (d3 != d1 && d3 != d2) {
                break;
            } else {
                d3 = randomDigit(); //refinds digit 3 if it is equal to digit one or two to ensure no duplicates
            }
        }
        String num = "";
        num += String.valueOf(d1); //puts it together in string to return
        num += String.valueOf(d2);
        num += String.valueOf(d3);
        return num;
    }

    String evaluateGuess(String target, String result) {
        String d1 = target.substring(0, 1);
        String d2 = target.substring(1, 2);
        String d3 = target.substring(2, 3);
        String i1 = result.substring(0, 1);
        String i2 = result.substring(1, 2);
        String i3 = result.substring(2, 3);
        String output = "";
        if (i1.equals(d1)) {
            output += "P"; //test for all P's first to ensure that P's will be printed first
        }
        if (i2.equals(d2)) {
            output += "P";
        }
        if (i3.equals(d3)) {
            output += "P";
        }
        if (i1.equals(d2) || i1.equals(d3)) {
            output += "N";
        }
        if (i2.equals(d1) || i2.equals(d3)) {
            output += "N";
        }
        if (i3.equals(d2) || i3.equals(d1)) {
            output += "N";
        }
        if (output.equals("")) { // if nothing matches, then string output will be empty and thus we know it should be a "Z"
            output += "Z";

        }
        return output;

    }

    void displayResults(String guess, String result) {
        out += guess;
        out += "\t";
        out += result;
        out += "\n";
        if (result.equals("PPP")) {
            out += "Game over! You won!";
            out += "\n";
            InputField.setEnabled(false); //prevents people from entering new numbers once game is over, allows them to do so again after new game
             EnterBut.setEnabled(false);
        }
        ResultsField.setText(out);
    }

}




